# Generated by Django 5.2 on 2025-05-30 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("shoe_name", models.TextField(blank=True, null=True)),
                ("gender", models.TextField(blank=True, null=True)),
                ("brand", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                (
                    "sku",
                    models.TextField(
                        blank=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("original_price", models.IntegerField(blank=True, null=True)),
                ("color_general", models.TextField(blank=True, null=True)),
                ("color", models.TextField(blank=True, null=True)),
                ("in_stock", models.IntegerField(blank=True, null=True)),
                ("available_sizes", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_urls", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "shoes",
                "ordering": ("shoe_name",),
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("size", models.TextField(default="N/A")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.product"
                    ),
                ),
            ],
        ),
    ]
